### PR TITLE
Database config page for when config is missing.

### LINKED ISSUE #244: Improve UI for invalid db credentials
When the app is first installed, if the db credentials are wrong, a scary error message is currently shown.

Please fix the UI for this and improve it so that a more graceful error message is shown which guides the user to create their config-local.php file.

Here's some text that you can use:

```
EndOfCodes is unable to run because you have not configured your database.
We will now create the file config-local.php for you. Please enter your database credentials below:
 Database name: [                 ]
 Database user: [                 ]
 Database password: [                 ]
 [ Create configuration ]
```

When [ Create configuration ] is clicked, your script can then create the config-local.php file for the user. If insufficient permissions are present, the script can show the appropriate contents and prompt the user to copy/paste them into a new file.

### PR DESCRIPTION
**Pull request by bugos**
Fixes #244.

image
image

### CODE REVIEW

**Comment by dionyziz** [comment]
Please fix the build.

**Comment by bugos** [comment]
Should we fix #281 here too?

File: controllers/dbconfig.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
+<?php
+    class DbconfigController extends ControllerBase {
+        public function create($user, $pass, $dbname) {
+            require_once 'models/database.php';
+
+            $entries = [ 'user'   => $user, 
+            			 'pass'   => $pass,
+            			 'dbname' => $dbname ];
```
Comment (dionyziz) [inline controllers/dbconfig.php]: nit: avoid tabs, use spaces for indentation

**Comment by dionyziz** [comment]
Let's fix #281 on a separate branch. You can create a branch sql_conf_cli with sql_conf as a parent and make a pull request (sql_conf_cli) that depends on this one (sql_conf) - you can mark dependency with a comment (depends #293); if you make changes to this one, you can merge back to the newer branch (git checkout sql_conf_cli; git merge sql_conf)

File: controllers/base.php [hunk 2]
```diff
@@ -128,7 +130,17 @@ protected function readHTTPAccept() {
...
+                if ( $this->resource != 'dbconfig' ) {
+                    dbInit();
+                }
+            }
+            catch ( DBException $e ) {
+                $resource = 'dbconfig';
+                $method = 'create';
+                $url = $resource . '/' . $method . '?' . 'error=' . $e->error . '&DbSaid=' . $e->DbSaid;
+                throw new RedirectException( $url );
+            }
```
Comment (dionyziz) [inline controllers/base.php:152]: Suggest moving `dbInit` to its own separate class method wrapper:

```
protected function dbInit() {
    dbInit();
}
```

Then the `if` section can be removed and the `dbconfig` controller can overload the `dbInit` method and make it empty.

File: controllers/base.php [hunk 3]
```diff
@@ -128,7 +130,17 @@ protected function readHTTPAccept() {
...
+            try {
+                if ( $this->resource != 'dbconfig' ) {
+                    dbInit();
+                }
+            }
+            catch ( DBException $e ) {
+                $resource = 'dbconfig';
+                $method = 'create';
+                $url = $resource . '/' . $method . '?' . 'error=' . $e->error . '&DbSaid=' . $e->DbSaid;
+                throw new RedirectException( $url );
```
Comment (dionyziz) [inline controllers/base.php]: Use `go`

File: controllers/dbconfig.php [hunk 4]
```diff
@@ -0,0 +1,27 @@
+<?php
+    class DbconfigController extends ControllerBase {
+        public function create($user, $pass, $dbname) {
```
Comment (dionyziz) [inline controllers/dbconfig.php]: nit: space after `(`, space before `)`

File: controllers/dbconfig.php [hunk 5]
```diff
@@ -0,0 +1,27 @@
+<?php
+    class DbconfigController extends ControllerBase {
+        public function create($user, $pass, $dbname) {
+            require_once 'models/database.php';
+
+            $entries = [ 'user'   => $user, 
+            			 'pass'   => $pass,
+            			 'dbname' => $dbname ];
+            $environment = 'development';
+            $content = createConfig( $entries, $environment);
```
Comment (dionyziz) [inline controllers/dbconfig.php]: nit: space before `)`

File: controllers/dbconfig.php [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+    class DbconfigController extends ControllerBase {
+        public function create($user, $pass, $dbname) {
+            require_once 'models/database.php';
+
+            $entries = [ 'user'   => $user, 
+            			 'pass'   => $pass,
+            			 'dbname' => $dbname ];
+            $environment = 'development';
+            $content = createConfig( $entries, $environment);
+            if ( empty($content) ) {
```
Comment (dionyziz) [inline controllers/dbconfig.php]: nit: space within `()`

File: controllers/dbconfig.php [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+            	throw new RedirectException( '' );
```
Comment (dionyziz) [inline controllers/dbconfig.php]: Use `go`

File: controllers/dbconfig.php [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+            }
+
+            require_once 'views/database/results.php';
+        }
+        public function createView( $error, $DbSaid ) {
```
Comment (dionyziz) [inline controllers/dbconfig.php]: Parameter variable names should start with a lower case letter; use `$dbSaid`

File: helpers/html.php [hunk 9]
```diff
@@ -169,12 +169,12 @@ public function output( $callable = false ) {
...
             ?><form <?php
-                if ( isset( $this->id ) ) {
+                if ( !empty( $this->id ) ) {
                     ?>id="<?php
                         echo htmlspecialchars( $this->id );
                     ?>" <?php
                 }
-                if ( isset( $this->attributes ) ) {
+                if ( !empty( $this->attributes ) ) {
                     foreach( $this->attributes as $key => $value ) {
```
Comment (dionyziz) [inline helpers/html.php]: nit: space after `foreach`

File: models/database.php [hunk 10]
```diff
@@ -1,12 +1,49 @@
...
     function dbInit() {
         global $config;
 
-        mysql_connect( $config[ 'db' ][ 'host' ], $config[ 'db' ][ 'user' ], $config[ 'db' ][ 'pass' ] ) or throwDBException( 'Failed to connect to MySQL: ' . mysql_error() );
+        $dbConnected = mysql_connect( $config[ 'db' ][ 'host' ], 
+        	           $config[ 'db' ][ 'user' ], 
+        	           $config[ 'db' ][ 'pass' ] );
+       	if ( !$dbConnected ) { 
+        	throw new DBException( 'Failed to connect to MySQL.', mysql_error() );
+    	}
```
Comment (dionyziz) [inline models/database.php]: nit: indentation

File: models/database.php [hunk 11]
```diff
@@ -1,12 +1,49 @@
...
-        throw new DBException( $message );
-    }
     function dbInit() {
         global $config;
 
-        mysql_connect( $config[ 'db' ][ 'host' ], $config[ 'db' ][ 'user' ], $config[ 'db' ][ 'pass' ] ) or throwDBException( 'Failed to connect to MySQL: ' . mysql_error() );
+        $dbConnected = mysql_connect( $config[ 'db' ][ 'host' ], 
+        	           $config[ 'db' ][ 'user' ], 
+        	           $config[ 'db' ][ 'pass' ] );
+       	if ( !$dbConnected ) {
```
Comment (dionyziz) [inline models/database.php]: nit: indentation

File: models/database.php [hunk 12]
```diff
@@ -1,12 +1,49 @@
...
-    function throwDBException( $message ) {
-        throw new DBException( $message );
-    }
     function dbInit() {
         global $config;
 
-        mysql_connect( $config[ 'db' ][ 'host' ], $config[ 'db' ][ 'user' ], $config[ 'db' ][ 'pass' ] ) or throwDBException( 'Failed to connect to MySQL: ' . mysql_error() );
+        $dbConnected = mysql_connect( $config[ 'db' ][ 'host' ], 
+        	           $config[ 'db' ][ 'user' ], 
+        	           $config[ 'db' ][ 'pass' ] );
```
Comment (dionyziz) [inline models/database.php]: nit: indentation

File: models/database.php [hunk 13]
```diff
@@ -1,12 +1,49 @@
...
+       	if ( !$dbConnected ) { 
+        	throw new DBException( 'Failed to connect to MySQL.', mysql_error() );
```
Comment (dionyziz) [inline models/database.php]: nit: indentation

File: models/database.php [hunk 14]
```diff
@@ -1,12 +1,49 @@
...
+    	}
+        $dbSelected = mysql_select_db( $config[ 'db' ][ 'dbname' ] );
+        if ( !$dbSelected ) { 
+        	throw new DBException( 'Failed to select MySQL database.', mysql_error() );
```
Comment (dionyziz) [inline models/database.php]: nit: indentation; etc. fix your tabs in the whole file

File: models/database.php [hunk 15]
```diff
@@ -1,12 +1,49 @@
...
+        }
+        if ( !empty($environment) ) {
+        	$config = $config[ $environment ];
+        	$config = $config[ 'db' ];
+        }
+        return $config;
+    }
+    function createConfig( $entries, $environment ) {
+    	$entries = ['db' => $entries];
+    	$entries = [$environment => $entries];
```
Comment (dionyziz) [inline models/database.php]: nit: spaces within `[]`

File: models/database.php [hunk 16]
```diff
@@ -1,12 +1,49 @@
...
+
+    	$path = 'config/config-local.php';
+    	$config = loadConfig();
+        $config = array_replace_recursive( $config, $entries );
+
+    	$content = '<?php' . PHP_EOL . 'return ' . var_export($config, true) . ';';
 
-        mysql_select_db( $config[ 'db' ][ 'dbname' ] ) or throwDBException( 'Failed to select MySQL database: ' . mysql_error() );
+    	if ( !file_exists($path) ) {
```
Comment (dionyziz) [inline models/database.php]: nit: spaces within `()`

File: models/db.php [hunk 17]
```diff
@@ -183,8 +183,12 @@ function dbListFields( $table ) {
     }  
 
     class DBException extends Exception {
-        public function __construct( $error ) {
-            parent::__construct( 'Database error: ' . $error );
+        public $error;
+        public $DbSaid;
+        public function __construct( $error, $DbSaid ) {
```
Comment (dionyziz) [inline models/db.php]: `$dbSaid`

File: models/database.php [hunk 18]
```diff
@@ -1,12 +1,49 @@
...
+    		touch( $path );
+    	}
+    	if ( is_writable( $path ) ) {
+    		$configSaved = is_numeric( file_put_contents( $path, $content ) );
+    	}
+    	if ( empty( $configSaved ) ) {
+    		return $content;
```
Comment (dionyziz) [inline models/database.php]: Consider throwing exception for erroneous case.

File: models/database.php [hunk 19]
```diff
@@ -1,12 +1,49 @@
...
+    	}
+    	return false; //Success
```
Comment (dionyziz) [inline models/database.php]: Don't use return values to indicate success/failure.

File: views/database/create.php [hunk 20]
```diff
@@ -0,0 +1,26 @@
...
+	$form = new Form( 'dbconfig', 'create' );
+	?><?php
+	$form->output( function( $self ) use ( &$configLocal ) {
+		$self->createLabel( 'user', 'Database User' );
+		$self->createInput( 'text', 'user', '', $configLocal[ 'user' ], [ 'class' => 'form-control input-lg' ] );
+		$self->createLabel( 'user', 'Database Password' );
+		$self->createInput( 'text', 'pass', '', $configLocal[ 'pass' ], [ 'class' => 'form-control input-lg' ] );
+		$self->createLabel( 'user', 'Database Name' );
+		$self->createInput( 'text', 'dbname', '', $configLocal[ 'dbname' ], [ 'class' => 'form-control input-lg' ] );	
+		$self->createSubmit( 'Create Configuration', [ 'class' => 'btn btn-primary' ] );
```
Comment (dionyziz) [inline views/database/create.php]: nit: indentation

File: views/database/results.php [hunk 21]
```diff
@@ -0,0 +1,11 @@
+<?php
+    require 'views/header.php';
+?>
+<p class="bg-warning">We were not able to save the configuration, probably because of insufficient permissions.</p>
+<p>Please copy/paste the following contents in endofcodes/config/config-local.php</p>
+<textarea class="form-control" rows="6"><?php
+	echo $content;
```
Comment (dionyziz) [inline views/database/results.php]: escape

File: views/database/create.php [hunk 22]
```diff
@@ -0,0 +1,26 @@
+<?php
+    require 'views/header.php';
+?>
+<h2>Database Error: <?php
+	echo $error;
+?></h2><p class="bg-danger">MySQL said: <?php
+	echo $DbSaid;
```
Comment (dionyziz) [inline views/database/create.php]: escape

File: views/database/create.php [hunk 23]
```diff
@@ -0,0 +1,26 @@
+<?php
+    require 'views/header.php';
+?>
+<h2>Database Error: <?php
+	echo $error;
```
Comment (dionyziz) [inline views/database/create.php]: escape

**Comment by dionyziz** [comment]
You can rebase your commits before you push them to achieve a cleaner history when you are experimenting. (But don't do it now that you've pushed them.)

File: helpers/php.php [hunk 24]
```diff
@@ -0,0 +1,8 @@
+<?php
+function issetShield( &$variable ) {
```
Comment (vitsalis) [inline helpers/php.php]: style

File: controllers/dbconfig.php [hunk 25]
```diff
@@ -0,0 +1,31 @@
+<?php
+    class DbconfigController extends ControllerBase {
+        protected function dbInit() {}
+
+        public function create( $user, $pass, $dbname ) {
+            require_once 'models/database.php';
+
+            $entries = [ 'user'   => $user,
```
Comment (dionyziz) [inline controllers/dbconfig.php]: nit: trailing whitespace

**Comment by dionyziz** [comment]
You must use 4 spaces for indentation. Tab is not an allowed character within our source code. These files have tabs in them and they must be replaced with 4 spaces:

```
dionyziz@erdos ~/endofcodes (sql_conf) % for i in `find . -iname "*.php" -type f`; do tab2space -unix $i > $i-new && mv $i-new $i; done
dionyziz@erdos ~/endofcodes (sql_conf*) % git status                                                                                    
On branch sql_conf
Your branch is up-to-date with 'bugos/sql_conf'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

modified:   controllers/dbconfig.php
modified:   database/migration/20131126210913_country.php
modified:   helpers/php.php
modified:   views/database/create.php
modified:   views/database/notwritable.php
```

File: controllers/base.php [hunk 26]
```diff
@@ -125,10 +125,22 @@ protected function readHTTPAccept() {
...
             $this->readHTTPAccept();
-            dbInit();
+            try {
+                $this->dbInit();
+            }
+            catch ( DBException $e ) {
+                $resource = 'dbconfig';
+                $method = 'create';
+                $arguments = get_object_vars( $e );
+                go( $resource, $method, $arguments );
```
Comment (dionyziz) [inline controllers/base.php]: Since `$resource` and `$method` variables are not additionally used, suggest you pass string constants directly to `go`; it doesn't add to code readability to have them as separate variables.

File: controllers/base.php [hunk 27]
```diff
@@ -139,10 +151,9 @@ public function dispatch( $get, $post, $files, $httpRequestMethod ) {
             }
             $method = $this->getControllerMethod( $get[ 'method' ], $httpRequestMethod );
             $vars = $this->getControllerVars( $get, $post, $files, $httpRequestMethod );
-            if ( !isset( $vars[ 'token' ] ) ) {
-                $token = '';
-            }
-            else {
+            
+            $token = '';
+            if ( isset( $vars[ 'token' ] ) ) {
```
Comment (dionyziz) [inline controllers/base.php:167]: Nice catch, thanks.

File: models/database.php [hunk 28]
```diff
@@ -1,12 +1,60 @@
...
-    function throwDBException( $message ) {
-        throw new DBException( $message );
-    }
     function dbInit() {
         global $config;
 
-        mysql_connect( $config[ 'db' ][ 'host' ], $config[ 'db' ][ 'user' ], $config[ 'db' ][ 'pass' ] ) or throwDBException( 'Failed to connect to MySQL: ' . mysql_error() );
+        $dbConnected = mysql_connect( $config[ 'db' ][ 'host' ], 
+                                      $config[ 'db' ][ 'user' ], 
+                                      $config[ 'db' ][ 'pass' ] );
```
Comment (dionyziz) [inline models/database.php]: This is more readable, nice.

File: models/database.php [hunk 29]
```diff
@@ -1,12 +1,60 @@
...
+        if ( !$dbConnected ) { 
+            throw new DBException( 'Failed to connect to MySQL.', mysql_error() );
+        }
+        $dbSelected = mysql_select_db( $config[ 'db' ][ 'dbname' ] );
+        if ( !$dbSelected ) { 
+            throw new DBException( 'Failed to select MySQL database.', mysql_error() );
+        }
+    } 
+    function loadConfig( $environment = '' ) {
```
Comment (dionyziz) [inline models/database.php]: Why do we need a separate function for this? Can't we use the regular config loading function here? (`getConfig` from `helpers/config.php`)

File: models/database.php [hunk 30]
```diff
@@ -1,12 +1,60 @@
...
+        $entries = [ $environment => $entries ];
+
+        $path = 'config/config-local.php';
+        $config = loadConfig();
+        $config = array_replace_recursive( $config, $entries );
+
+        $content = formatConfig( $config );
 
-        mysql_select_db( $config[ 'db' ][ 'dbname' ] ) or throwDBException( 'Failed to select MySQL database: ' . mysql_error() );
+        @touch( $path ); // is_writable will return false if this fails.
```
Comment (dionyziz) [inline models/database.php]: You should read the return value of `touch` which is boolean `true`/`false` for success/failure to determine the ability to touch the file. `$touched = @touch( ... );`

File: models/database.php [hunk 31]
```diff
@@ -1,12 +1,60 @@
...
+        if ( is_writable( $path ) ) {
```
Comment (dionyziz) [inline models/database.php]: Avoid checking writability at a different step from actually writing the file, to avoid race conditions; just use the return value of `touch`.

File: models/database.php [hunk 32]
```diff
@@ -1,12 +1,60 @@
...
+            $configSaved = is_numeric( file_put_contents( $path, $content ) );
```
Comment (dionyziz) [inline models/database.php]: Suggest using the return value of `file_put_contents` directly and comparing against `=== false`; this is the typical way it's done in PHP.

File: models/database.php [hunk 33]
```diff
@@ -1,12 +1,60 @@
...
+        }
+        if ( empty( $configSaved ) ) {
+            throw new DBExceptionNotWritable( $content );
+        }
+    }
+    class DBExceptionNotWritable extends DBException {
```
Comment (dionyziz) [inline models/database.php]: This error is not particularly db-related. Suggest moving to `helpers/file.php` and calling it `FileNotWritableException`. Also, all exceptions must end in `Exception` to be consistent with the rest of the codebase.

File: models/database.php [hunk 34]
```diff
@@ -1,12 +1,60 @@
...
+    function formatConfig( $config ) {
+        $content = '<?php' . PHP_EOL . 'return ' . var_export( $config, true ) . ';' . PHP_EOL . '?>';
+        $content = str_replace( '  ', '    ', $content ); //convert 2 spaces to 4
+        $content = preg_replace( '/\s*array \(/', ' [', $content );
+        $content = str_replace( ')', ']', $content );
+        return $content;
+    }
+    function createConfig( $entries, $environment ) {
+        $entries = [ 'db'         => $entries ];
+        $entries = [ $environment => $entries ];
```
Comment (dionyziz) [inline models/database.php]: Not sure why you are setting the `$entries` variable twice; however, the second time the variable is set, the first value is lost.

File: controllers/dbconfig.php [hunk 35]
```diff
@@ -0,0 +1,31 @@
+<?php
+    class DbconfigController extends ControllerBase {
+        protected function dbInit() {}
+
+        public function create( $user, $pass, $dbname ) {
+            require_once 'models/database.php';
+
+            $entries = [ 'user'   => $user, 
+                         'pass'   => $pass,
+                         'dbname' => $dbname ];
```
Comment (dionyziz) [inline controllers/dbconfig.php]: Better written using `compact`

File: models/database.php [hunk 36]
```diff
@@ -1,12 +1,60 @@
...
+
+        $path = 'config/config-local.php';
+        $config = loadConfig();
+        $config = array_replace_recursive( $config, $entries );
```
Comment (dionyziz) [inline models/database.php]: Based on the new configuration loader, only the entries that differ from `config.php` need to be specified in `config-local.php`; `array_replace_recursive` is used during config loading. Therefore, we can just write the `$entries` directly to the config at this point.

File: controllers/dbconfig.php [hunk 37]
```diff
@@ -0,0 +1,31 @@
...
+            catch ( DBExceptionNotWritable $e ) {
+                $content = $e->content;
+                require_once 'views/database/notwritable.php';
+            }
+        }
+        public function createView( $error, $dbSaid ) {
+            require_once 'models/database.php';
+
+            $environment = 'development';
+            $configLocal = loadConfig( $environment );
```
Comment (dionyziz) [inline controllers/dbconfig.php]: Use an `array_merge_recursive` here instead of `issetShield`.

File: helpers/php.php [hunk 38]
```diff
@@ -0,0 +1,8 @@
+<?php
+    function issetShield( &$variable ) {
+        if ( !isset( $variable ) ) {
+            $variable = ''; 
+        }
+        return $variable;
+    }
+?>
```
Comment (dionyziz) [inline helpers/php.php]: Not needed.

File: controllers/base.php [hunk 39]
```diff
@@ -125,10 +119,22 @@ protected function readHTTPAccept() {
...
+            }
+            catch ( DBException $e ) {
+                $arguments = get_object_vars( $e );
+                go( 'dbconfig', 'create', $arguments );
+            }
+        }
         protected function init() {
-            $this->loadConfig();
+            $this->getEnvironment();
+            global $config;
```
Comment (dionyziz) [inline controllers/base.php]: Move global declarations to the top of function; leave a new line afterwards. This make it clear, when looking at a function, what is global and what isn't.

File: helpers/config.php [hunk 40]
```diff
@@ -15,15 +15,40 @@ function getBase() {
...
+        $path = 'config/config-local.php';
+        $touched = @touch( $path );
+        if ( $touched ) {
+            $configSaved = file_put_contents( $path, $content ) !== false;
+        }
+        if ( empty( $configSaved ) ) {
+            throw new FileNotWritableException( $path, $content );
+        }
+        global $config;
+        $config = array_replace_recursive( $config, $entries );
```
Comment (dionyziz) [inline helpers/config.php]: Why do you need to change the `$config` variable here?

File: helpers/config.php [hunk 41]
```diff
@@ -15,15 +15,40 @@ function getBase() {
...
+    function updateConfig( $entries, $environment ) {
+        $entries = [ $environment => $entries ];
+
+        $content = formatConfig( $entries );
+        $path = 'config/config-local.php';
+        $touched = @touch( $path );
+        if ( $touched ) {
+            $configSaved = file_put_contents( $path, $content ) !== false;
+        }
+        if ( empty( $configSaved ) ) {
```
Comment (dionyziz) [inline helpers/config.php]: Maybe move this `if` inside the `if` above? It will only possibly succeed when the `touch` has succeeded, so it makes for more readable code - if you can touch, then try to save, but if it didn't save then throw.

File: helpers/html.php [hunk 42]
```diff
@@ -169,13 +169,13 @@ public function output( $callable = false ) {
...
             ?><form <?php
-                if ( isset( $this->id ) ) {
+                if ( !empty( $this->id ) ) {
                     ?>id="<?php
                         echo htmlspecialchars( $this->id );
                     ?>" <?php
                 }
-                if ( isset( $this->attributes ) ) {
-                    foreach( $this->attributes as $key => $value ) {
+                if ( !empty( $this->attributes ) ) {
```
Comment (dionyziz) [inline helpers/html.php]: I think we can initialize `$this->attributes` to `[]` and then execute the `foreach` without a guard.

File: views/database/create.php [hunk 43]
```diff
@@ -0,0 +1,27 @@
...
+    $form = new Form( 'dbconfig', 'create' );
+    $form->output( function( $self ) use ( &$oldConfig ) {
+        $self->createLabel( 'user', 'Database User' );
+        $self->createInput( 'text', 'user', '', $oldConfig[ 'db' ][ 'user' ], [ 'class' => 'form-control input-lg' ] );
+
+        $self->createLabel( 'user', 'Database Password' );
+        $self->createInput( 'text', 'pass', '', $oldConfig[ 'db' ][ 'pass' ], [ 'class' => 'form-control input-lg' ] );
+
+        $self->createLabel( 'user', 'Database Name' );
+        $self->createInput( 'text', 'dbname', '', $oldConfig[ 'db' ][ 'dbname' ], [ 'class' => 'form-control input-lg' ] );
```
Comment (dionyziz) [inline views/database/create.php]: Trailing whitespace

File: views/database/create.php [hunk 44]
```diff
@@ -0,0 +1,27 @@
...
+        $self->createLabel( 'user', 'Database User' );
+        $self->createInput( 'text', 'user', '', $oldConfig[ 'db' ][ 'user' ], [ 'class' => 'form-control input-lg' ] );
+
+        $self->createLabel( 'user', 'Database Password' );
+        $self->createInput( 'text', 'pass', '', $oldConfig[ 'db' ][ 'pass' ], [ 'class' => 'form-control input-lg' ] );
+
+        $self->createLabel( 'user', 'Database Name' );
+        $self->createInput( 'text', 'dbname', '', $oldConfig[ 'db' ][ 'dbname' ], [ 'class' => 'form-control input-lg' ] );  
+
+        $self->createSubmit( 'Create Configuration', [ 'class' => 'btn btn-primary' ] );
```
Comment (dionyziz) [inline views/database/create.php]: Trailing whitespace

File: views/database/create.php [hunk 45]
```diff
@@ -0,0 +1,27 @@
...
+<h2>Database Error: <?php
+    echo $error;
+?></h2><p class="bg-danger">MySQL said: <?php
+    echo $dbSaid;
+?></p>
+<p>EndOfCodes is unable to run because you have not configured your database.</p>
+<p>We will now create the file config-local.php for you. Please enter your database credentials below: </p>
+<?php
+    $form = new Form( 'dbconfig', 'create' );
+    $form->output( function( $self ) use ( &$oldConfig ) {
```
Comment (dionyziz) [inline views/database/create.php]: No need to pass by reference any more.

**Comment by dionyziz** [comment]
Our error style requires extra padding. See the login page:

screen shot 2014-05-19 at 11 49 44 am

Talk to @pkakelas about using bootstrap/CSS to achieve this effect.

File: helpers/config.php (hunk 40 above)
Comment (bugos) [inline helpers/config.php]: Since we are updating the config files, we should also update the `$config` variable. 
For the purposes of this pull request this is not needed beacause we are using `go()` right after, so the config gets reloaded. In other cases though, it may be necessary.

File: views/database/create.php [hunk 46]
```diff
@@ -0,0 +1,27 @@
...
+        $self->createLabel( 'user', 'Database User' );
+        $self->createInput( 'text', 'user', '', $oldConfig[ 'db' ][ 'user' ], [ 'class' => 'form-control input-lg' ] );
```
Comment (pkakelas) [inline views/database/create.php]: Why do you use .input-lg? My suggestion is to use only .form-control and reduce the width of the form

File: views/database/create.php [hunk 47]
```diff
@@ -0,0 +1,27 @@
+<?php
+    require 'views/header.php';
+?>
+<h2>Database Error: <?php
+    echo $error;
+?></h2><p class="bg-danger">MySQL said: <?php
```
Comment (pkakelas) [inline views/database/create.php]: You should use class="alert alert-danger" here.

File: views/database/create.php [hunk 48]
```diff
@@ -0,0 +1,27 @@
...
+        $self->createLabel( 'user', 'Database Password' );
+        $self->createInput( 'text', 'pass', '', $oldConfig[ 'db' ][ 'pass' ], [ 'class' => 'form-control input-lg' ] );
+
+        $self->createLabel( 'user', 'Database Name' );
+        $self->createInput( 'text', 'dbname', '', $oldConfig[ 'db' ][ 'dbname' ], [ 'class' => 'form-control input-lg' ] );  
+
+        $self->createSubmit( 'Create Configuration', [ 'class' => 'btn btn-primary' ] ); 
+    } );
+
+    require 'views/footer.php';
```
Comment (pkakelas) [inline views/database/create.php]: Check out #302. You should require 'views/footer/view.php'

File: views/database/notwritable.php [hunk 49]
```diff
@@ -0,0 +1,11 @@
+<?php
+    require 'views/header.php';
+?>
+<p class="bg-warning">We were not able to save the configuration, probably because of insufficient permissions.</p>
+<p>Please copy/paste the following contents in endofcodes/config/config-local.php</p>
+<textarea class="form-control" rows="8"><?php
+    echo $content;
+?></textarea>
+<?php
+    require 'views/footer.php';
```
Comment (pkakelas) [inline views/database/notwritable.php]: Check out #302. You should require 'views/footer/view.php'

File: views/database/create.php (hunk 46 above)
Comment (bugos) [inline views/database/create.php]: How do I reduce the width of the form?

**Comment by bugos** [comment]
Still working on this. Please comment on the new controller. Ignore minor style or code errors for now.
untitled
untitled2

**Comment by dionyziz** [comment]
New screenshots are looking nice :+1:

File: static/style/dbconfig/create.css [hunk 50]
```diff
@@ -0,0 +1,3 @@
+#dbconfig {
+    width: 500px;
+}
```
Comment (dionyziz) [inline static/style/dbconfig/create.css]: Add new line to end of file.

File: helpers/config.php [hunk 51]
```diff
@@ -15,15 +15,44 @@ function getBase() {
...
-        $config = $config[ $env ];
+        $config = $config[ $environment ];
         $config[ 'root' ] = getcwd();
         $config[ 'base' ] = getBase();
         return $config;
     }
+    function formatConfig( $config ) {
+        $content = '<?php' . PHP_EOL . 'return ' . var_export( $config, true ) . ';' . PHP_EOL . '?>';
+
+        //Convert 2-space indentation to 4-space.
```
Comment (pkakelas) [inline helpers/config.php]: I suggest you to put the comments next to the line and not above it.

File: helpers/file.php [hunk 52]
```diff
@@ -0,0 +1,22 @@
+<?php
+    function safeWrite( $filename, $content ) {
+        if ( !file_exists( $filename ) ) {
+            @touch( $filename );
+        }
+        if ( is_writable( $filename ) ) {
```
Comment (pkakelas) [inline helpers/file.php]: if ( is_writable( $filename ) ) {
    if ( !file_put_contents( $filename, $content ) ) {
        throw new FileNotWritableException( $filename, $content );
    }
}

File: helpers/config.php (hunk 51 above)
Comment (dionyziz) [inline helpers/config.php]: I disagree, this looks fine to me, especially since they are larger comments.

File: helpers/file.php (hunk 52 above)
Comment (dionyziz) [inline helpers/file.php]: `file_put_contents` should not be used in an `if` directly like that; in PHP, it's best to separate checks (`if`) from actions (`file_put_contents`). His code is fine. I agree with moving the `if` check for `$success` emptiness to within the `is_writable` if however.

File: helpers/file.php [hunk 53]
```diff
@@ -0,0 +1,22 @@
+<?php
+    function safeWrite( $filename, $content ) {
```
Comment (dionyziz) [inline helpers/file.php]: unit test

File: helpers/config.php [hunk 54]
```diff
@@ -15,15 +15,44 @@ function getBase() {
...
             $configLocal = require 'config/config-local.php';
             $config = array_replace_recursive( $config, $configLocal );
         }
-        $config = $config[ $env ];
+        $config = $config[ $environment ];
         $config[ 'root' ] = getcwd();
         $config[ 'base' ] = getBase();
         return $config;
     }
+    function formatConfig( $config ) {
```
Comment (dionyziz) [inline helpers/config.php:29]: unit test

File: helpers/config.php [hunk 55]
```diff
@@ -15,15 +15,44 @@ function getBase() {
...
+        $content = str_replace( '  ', '    ', $content );
+        //Replace array(...) with [...].
+        $content = preg_replace( '/\s*array \(/', ' [', $content );
+        $content = str_replace( ')', ']', $content );
+        //Indent code inside <?php tags.
+        $content = preg_replace( '/(^[^(<)|(\?)])/m', '    $1', $content );
+
+        return $content;
+    }
+    function updateConfig( $entries, $environment ) {
```
Comment (dionyziz) [inline helpers/config.php:46]: unit test

File: models/database.php [hunk 56]
```diff
@@ -1,12 +0,0 @@
-<?php
```
Comment (dionyziz) [inline models/database.php:1]: Nice that this is finally removed.

File: helpers/file.php (hunk 52 above)
Comment (bugos) [inline helpers/file.php]: The `if` check for `$success` is on purpose outside the `is_writable` `if` so we can handle the case when `is_writable` returns false. In that case `$success` remains unset and we throw an exception.

Comment (dionyziz) [inline helpers/file.php]: I see.

**Comment by dionyziz** [comment]
fix build

File: controllers/base.php [hunk 57]
```diff
@@ -93,16 +93,15 @@ protected function callWithNamedArgs( $methodReflection, $callable, $vars ) {
...
-            else {
-                $env = $this->environment;
+                $this->environment = getEnv( 'ENVIROMENT' );
             }
-            $config = getConfig( $env );
+        }
+        protected function getConfig() {
+            global $config;
+
+            $config = getConfig( $this->environment );
```
Comment (vitsalis) [inline controllers/base.php]: having the same function name as the method is confusing..

File: helpers/config.php [hunk 58]
```diff
@@ -1,29 +1,79 @@
...
+        $content = str_replace( '  ', '    ', $content );
+        // Replace array(...) with [...].
+        $content = preg_replace( '/\s*array \(/', ' [', $content );
+        $content = str_replace( ')', ']', $content );
+        // Indent code inside <?php tags.
+        $content = preg_replace( '/(^[^(<)|(\?)])/m', '    $1', $content );
+
+        return $content;
+    }
+    function array_diff_recursive( $minuend, $subtrahend = [] ) {
```
Comment (vitsalis) [inline helpers/config.php]: `$minuend` and `$subtrahend`? what do these mean?

File: helpers/config.php [hunk 59]
```diff
@@ -1,29 +1,79 @@
...
+            $old_entries = include $configPath;
+            $entries = array_replace_recursive( $old_entries, $entries );
+        }
+        $config = array_replace_recursive( $config, $entries[ $environment ] );
+        $config = array_diff_recursive( $config ); // Remove empty entries.
+
+        $entries = array_diff_recursive( $entries ); // Remove empty entries.
+        $content = formatConfig( $entries );
+        safeWrite( $configPath, $content );
+
```
Comment (vitsalis) [inline helpers/config.php]: empty line

File: helpers/html.php [hunk 60]
```diff
@@ -41,6 +41,7 @@ public static function isValidType( $type ) {
         public function __construct( $resource = '', $method = '' ) {
             $this->resource = $resource;
             $this->method = $method;
+            $this->attributes = [];
```
Comment (vitsalis) [inline helpers/html.php]: Better remove this and set `attrbutes` as an empty array when `attributes` is defined.
`public $attributes = [];`

File: controllers/base.php (hunk 57 above)
Comment (bugos) [inline controllers/base.php]: I aggree. I think we should change the original `getConfig()` name to `loadConfig()`.

File: tests/helpers/config.php [hunk 61]
```diff
@@ -0,0 +1,52 @@
...
+                ]
+            ];
+            $output = formatConfig( $config );
+
+            $filename = 'config-test.php';
+            file_put_contents( $filename, $output );
+            $loaded = require $filename;
+            unlink( $filename );
+
+            $this->assertTrue( $loaded == $config );
```
Comment (dionyziz) [inline tests/helpers/config.php]: Use `assertEquals` or `assertSame`.

File: helpers/config.php [hunk 62]
```diff
@@ -1,29 +1,83 @@
...
+    function formatConfig( $config ) {
+        $content = '<?php' . PHP_EOL . 'return ' . var_export( $config, true ) . ';' . PHP_EOL . '?>';
+
+        // Convert 2-space indentation to 4-space.
+        $content = str_replace( '  ', '    ', $content );
+        // Replace array(...) with [...].
+        $content = preg_replace( '/\s*array \(/', ' [', $content );
+        $content = str_replace( ')', ']', $content );
+        // Indent code inside <?php tags.
+        $content = preg_replace( '/(^[^(<)|(\?)])/m', '    $1', $content );
```
Comment (dionyziz) [inline helpers/config.php:40]: Unit test that style is corrected. Suggest you just assert that the code outputted by the `formatConfig` function is simply a particular hard-coded constant string, with the correct formatting, when a constant is given as an input. You can use a prototype fixture file to compare against.

File: helpers/config.php [hunk 63]
```diff
@@ -1,29 +1,83 @@
...
+
+        return $content;
+    }
+    // Returns the elements of $minuend that are not elements of $subtrahend.
+    // Ignores NULL elements.
+    function array_diff_recursive( $minuend, $subtrahend = [] ) {
```
Comment (dionyziz) [inline helpers/config.php]: Move to separate array helper. Unit test.

File: helpers/config.php [hunk 64]
```diff
@@ -1,29 +1,83 @@
...
+        $difference = [];
+        foreach ( $minuend as $key => $value ) {
+            if ( $value === NULL ) {
+                continue;
+            }
```
Comment (dionyziz) [inline helpers/config.php]: Why is this explicit check for `NULL` needed?

File: helpers/config.php [hunk 65]
```diff
@@ -1,29 +1,83 @@
...
+            if ( is_array( $value ) && $value !== [] ) {
+                if ( !isset( $subtrahend[ $key ] ) ) {
+                    $subtrahend[ $key ] = [];
+                }
+                $result = array_diff_recursive( $value, $subtrahend[ $key ] );
+                if ( $result !== [] ) {
+                    $difference[ $key ] = $result;
+                }
+            }
+            elseif ( !isset( $subtrahend[ $key ] ) || $value !== $subtrahend[ $key ] ) {
```
Comment (dionyziz) [inline helpers/config.php]: nit: `else if`

File: helpers/config.php (hunk 63 above)
Comment (dionyziz) [inline helpers/config.php]: What do the argument values mean?

File: tests/helpers/config.php [hunk 66]
```diff
@@ -0,0 +1,52 @@
...
+            $oldLocalConfig = [];
+            if ( file_exists( 'config/config-local.php' ) ) {
+                $oldLocalConfig = include 'config/config-local.php';
+            }
+
+            $entries = [ 'some_entry' => 'some_value', 'some_array' => [ 'jpg', 'png' ] ];
+            $environment = 'test';
+
+            updateConfig( $entries, $environment );
+            $this->assertEquals( $entries, array_diff_recursive( $config, $oldConfig ) );
```
Comment (dionyziz) [inline tests/helpers/config.php]: This is not a good test; you're just repeating the implementation of the function. Instead, you should test with a particular case. Just set `$config` to something constant and make sure your function does what is expected on it.

File: tests/helpers/config.php [hunk 67]
```diff
@@ -0,0 +1,52 @@
...
+
+            $localConfig = include 'config/config-local.php';
+            $this->assertEquals( [ $environment => $entries ], array_diff_recursive( $localConfig, $oldLocalConfig ) );
```
Comment (dionyziz) [inline tests/helpers/config.php]: Similarly

File: tests/helpers/config.php [hunk 68]
```diff
@@ -0,0 +1,52 @@
...
+            $this->assertTrue( $loaded == $config );
+        }
+        public function testUpdateConfig() {
+            global $config;
+
+            $oldConfig = $config;
+            $oldLocalConfig = [];
+            if ( file_exists( 'config/config-local.php' ) ) {
+                $oldLocalConfig = include 'config/config-local.php';
+            }
```
Comment (dionyziz) [inline tests/helpers/config.php]: Better written in `setUp`

File: tests/helpers/config.php [hunk 69]
```diff
@@ -0,0 +1,52 @@
...
+            updateConfig( $entries, $environment );
+            $this->assertEquals( $entries, array_diff_recursive( $config, $oldConfig ) );
+
+            $localConfig = include 'config/config-local.php';
+            $this->assertEquals( [ $environment => $entries ], array_diff_recursive( $localConfig, $oldLocalConfig ) );
+
+            $nullEntries = array_map( function( $entry ) {
+                return NULL;
+            }, $entries);
+            updateConfig( $nullEntries, $environment ); // Clean up.
```
Comment (dionyziz) [inline tests/helpers/config.php]: Better written in `tearDown`. If the unit test fails, you still need to clean up.

File: tests/helpers/config.php [hunk 70]
```diff
@@ -0,0 +1,52 @@
...
+            $this->assertEquals( $oldConfig, $config );
+
+            $localConfig = include 'config/config-local.php';
+            $this->assertEquals( $oldLocalConfig, $localConfig );
```
Comment (dionyziz) [inline tests/helpers/config.php]: What does this assertion test for? It seems that this is just restoring the old config file and we've already tested whether `updateConfig` works.

File: tests/helpers/file.php [hunk 71]
```diff
@@ -0,0 +1,29 @@
...
+        public function testSafeWrite() {
+            $content = 'I shall be written safely';
+            $filename = 'message.txt';
+            safeWrite( $filename, $content );
+            $read = file_get_contents( $filename );
+            $this->assertEquals( $content, $read );
+
+            chmod( $filename, 0444 ); //Read permission for everybody.
+            $newContent = 'I have a bad premonition';
+            $catched = false;
```
Comment (dionyziz) [inline tests/helpers/file.php]: `$caught`

File: tests/helpers/file.php [hunk 72]
```diff
@@ -0,0 +1,29 @@
...
+            try {
```
Comment (dionyziz) [inline tests/helpers/file.php]: You can use our new `assertThrows` for cleaner tests.

File: tests/helpers/file.php [hunk 73]
```diff
@@ -0,0 +1,29 @@
...
+            }
+            catch ( FileNotWritableException $e ) {
+                $catched = true;
+                $this->assertEquals( $filename, $e->filename );
+                $this->assertEquals( $newContent, $e->content );
+            }
+            $this->assertTrue( $catched );
+
+            chmod( $filename, 0666 );
+            unlink($filename);
```
Comment (dionyziz) [inline tests/helpers/file.php]: You should also test for un-touchable files: Non-existing file in a non-writable directory.

File: models/db.php [hunk 74]
```diff
@@ -20,7 +34,7 @@ function db( $sql, $bind = [] ) {
         $finalsql = strtr( $sql, $bind );
         $res = mysql_query( $finalsql );
         if ( $res === false ) {
-            throw new DBException( mysql_error() );
+            throw new DBException( '', mysql_error() );
```
Comment (dionyziz) [inline models/db.php]: `'Failed to execute query'`?

File: models/db.php [hunk 75]
```diff
@@ -180,11 +194,19 @@ function dbListTables() {
...
+        public $error;
+        public $dbSaid;
+        public function __construct( $error, $dbSaid = '' ) {
+            $this->error = $error;
+            $this->dbSaid = $dbSaid;
+            $message = 'Database error: ' . $error;
+            if ( !empty( $dbSaid ) ) {
+                $message .= ' MySQL said: ' . $dbSaid;
+            }
+            parent::__construct(  );
```
Comment (dionyziz) [inline models/db.php]: nit: empty `()` should not have spaces within

File: static/style/dbconfig/create.css [hunk 76]
```diff
@@ -0,0 +1,3 @@
+#dbconfig {
```
Comment (dionyziz) [inline static/style/dbconfig/create.css:1]: Is this css file loaded?

File: views/database/create.php [hunk 77]
```diff
@@ -0,0 +1,32 @@
+<?php
+    require 'views/header.php';
+
+    if ( !empty( $error ) ) {
+        ?><h2>Database Error: <?php
+            echo $error;
```
Comment (dionyziz) [inline views/database/create.php]: escape

File: views/database/create.php [hunk 78]
```diff
@@ -0,0 +1,32 @@
+<?php
+    require 'views/header.php';
+
+    if ( !empty( $error ) ) {
+        ?><h2>Database Error: <?php
+            echo $error;
+        ?></h2><?php
+            if ( !empty( $dbSaid ) ) {
+                ?><p class="alert alert-danger">MySQL said: <?php
+                    echo $dbSaid;
```
Comment (dionyziz) [inline views/database/create.php]: escape

File: views/database/create.php [hunk 79]
```diff
@@ -0,0 +1,32 @@
...
+        ?></h2><?php
+            if ( !empty( $dbSaid ) ) {
+                ?><p class="alert alert-danger">MySQL said: <?php
+                    echo $dbSaid;
+                ?></p><?php
+            }
+        ?><div id="dbconfig">
+        <p>EndOfCodes is unable to run because you have not configured your database. We will now create the file config-local.php for you. Please enter your database credentials below: </p><?php
+    }
+    $form = new Form( 'dbconfig', 'create' );
```
Comment (dionyziz) [inline views/database/create.php]: For a different branch: I see we're using some pretty standard bootstrap classes in almost all of our forms. Consider extending the `Form` class into a `BootstrapForm` class to accommodate for this use and DRY. @pkakelas may be interested in doing this.

File: views/database/notwritable.php [hunk 80]
```diff
@@ -0,0 +1,11 @@
+<?php
+    require 'views/header.php';
+?>
+<p class="alert alert-warning">We were not able to save the configuration, probably because of insufficient permissions.</p>
+<p>Please copy/paste the following contents in endofcodes/config/config-local.php</p>
+<textarea class="form-control" rows="8"><?php
+    echo $content;
```
Comment (dionyziz) [inline views/database/notwritable.php]: escape

File: helpers/config.php (hunk 63 above)
Comment (bugos) [inline helpers/config.php]: I though these names would be descriptive but they seem to be confusing. Can you guys think of two better names for the function arguments? 
http://www.mathsisfun.com/definitions/minuend.html
cc: @VitSalis

File: tests/helpers/config.php (hunk 66 above)
Comment (bugos) [inline tests/helpers/config.php]: I don't see how I am reapeating the implementation here. I am using some constant entries as an input and I am testing if the are actually inserted into config and written in the local config file. Then I remove them and I test again.

File: static/style/dbconfig/create.css (hunk 76 above)
Comment (bugos) [inline static/style/dbconfig/create.css:1]: Yes https://github.com/dionyziz/endofcodes/pull/293/files#diff-eedccb574d1fb01ebacc6e6e92e5b974R23

File: tests/helpers/config.php (hunk 70 above)
Comment (bugos) [inline tests/helpers/config.php]: That `updateConfig()` is capable of deleting entries that are set to NULL, leaving the remaining entries intact.

**Comment by dionyziz** [comment]
Please fix build.

File: tests/helpers/file.php [hunk 81]
```diff
@@ -0,0 +1,71 @@
...
+                'FileNotWritableException',
+                'safeWrite() must throw an Exception when attempting to write a read-only file',
+                function( FileNotWritableException $e ) {
+                    $this->assertEquals( $this->filename, $e->filename );
+                    $this->assertEquals( $this->content, $e->content );
+                }
+            );
+        }
+        public function testSafeWrite() {
+            //$this->readOnlyDirectory(); // This test is not functional yet.
```
Comment (bugos) [inline tests/helpers/file.php]: This is not directly related with this pull request. It will be fixed - I hope - for #243.

File: tests/helpers/file.php [hunk 82]
```diff
@@ -0,0 +1,71 @@
...
+                    safeWrite( $this->filename, $this->content );
+                },
+                'FileNotWritableException',
+                'safeWrite() must not throw an Exception when attempting to write to an empty, writable directory'
+            );
+            $read = file_get_contents( $this->filename );
+            $this->assertEquals( $this->content, $read, 'Content read must be the same passed to safeWrite()' );
+        }
+        private function readOnlyFile() {
+            chmod( $this->filename, 0444 );
```
Comment (dionyziz) [inline tests/helpers/file.php]: I'm confused when it pertains to the success of this. Does this depend on the file existing? If yes, where is the file created prior to this being called?

File: tests/helpers/config.php [hunk 83]
```diff
@@ -0,0 +1,76 @@
...
+        public function testUpdateConfig() {
+            global $config;
+
+            $entries = [ 'some_entry' => 'some_value', 'some_array' => [ 'jpg', 'png' ] ];
+            $environment = 'test';
+
+            // Let's try to add some entries.
+            updateConfig( $entries, $environment );
+            $this->assertSame( $entries, array_diff_recursive( $config, $this->originalConfig ), 'The new entries must exist in the $config after calling updateConfig()' );
+            $this->assertSame( [ $environment => $entries ], array_diff_recursive( include $this->localConfigPath, $this->originalLocalConfig ), 'The new entries must exist in the local-config.php after calling updateConfig()' );
```
Comment (dionyziz) [inline tests/helpers/config.php:47]: I suggest you don't use `array_diff_recursive` in this test. Just precompute what it should output and hardcode it here.

File: helpers/config.php (hunk 63 above)
Comment (dionyziz) [inline helpers/config.php]: Ah, I see where these come from. No, they look fine. I didn't know the English terms, but after reading your link they seem plausible and readable.

File: helpers/array.php [hunk 84]
```diff
@@ -0,0 +1,28 @@
...
+                    $difference[ $key ] = $result;
+                }
+            }
+            else if ( !isset( $subtrahend[ $key ] ) || $value !== $subtrahend[ $key ] ) {
+                $difference[ $key ] = $value;
+            }
+        }
+        return $difference;
+    }
+?>
```
Comment (dionyziz) [inline helpers/array.php]: nit: new line

File: tests/helpers/config.php [hunk 85]
```diff
@@ -0,0 +1,76 @@
+<?php
+    class ConfigHelperTest extends UnitTest {
+        public function setUp() {
+            global $config;
+
+            $this->tempConfigFile = 'tests/helpers/config-test.temp';
+            touch( $this->tempConfigFile );
+            $this->prototypeContent = file_get_contents( 'tests/helpers/formatConfig.prototype' );
+            // Convert all newlines to \n.
+            $this->prototypeContent = preg_replace( '/(\r\n|\r|\n)/', "\n", $this->prototypeContent );
```
Comment (dionyziz) [inline tests/helpers/config.php]: Why can't these be included in the prototype?

File: tests/helpers/file.php (hunk 82 above)
Comment (bugos) [inline tests/helpers/file.php]: This function uses the file created by emptyWritableDirectory() that is called just before. I will add a comment.

File: tests/helpers/config.php (hunk 83 above)
Comment (bugos) [inline tests/helpers/config.php:47]: I prefer this way because otherwise I would have to hardcode also the config.php and config-local.php files.

**Comment by dionyziz** [comment]
Please merge from master.

**Comment by dionyziz** [comment]
Please merge from master again.

File: helpers/array.php [hunk 86]
```diff
@@ -0,0 +1,28 @@
+<?php
+    // Returns the elements of $minuend that are not elements of $subtrahend.
+	// This extends array_diff_assoc() to multidimentional arrays.
+	//
+    // If any elements of $minuend are set to NULL they are not included in the $difference.
+	// This enables us to use $array = array_diff_recursive( $array ) to remove NULL elements from an array.
```
Comment (dionyziz) [inline helpers/array.php]: nit: Use 4 spaces instead of tabs

File: tests/helpers/array.php [hunk 87]
```diff
@@ -0,0 +1,53 @@
...
+                ]
+            ];
+            $this->assertSame( [
+                    'email' => 'bugos@gmail.com',
+                    'technologies' => [
+                        'php' => 3
+                    ]
+                ],
+                array_diff_recursive( $updatedArray, $array ),
+                'array_diff_recursive() must return the entries in $updatedArray that does not exist in $array.'
```
Comment (dionyziz) [inline tests/helpers/array.php]: ..."that _do_ not exist in \$array."

File: helpers/config.php [hunk 88]
```diff
@@ -1,29 +1,63 @@
...
             $config = array_replace_recursive( $config, $configLocal );
         }
-        $config = $config[ $env ];
+        $config = $config[ $environment ];
         $config[ 'root' ] = getcwd();
         $config[ 'base' ] = getBase();
         return $config;
     }
+    function formatConfig( $config ) {
+        $content = '<?php' . "\n"
```
Comment (dionyziz) [inline helpers/config.php:30]: Consider combining into `"<?php\n"`

File: helpers/config.php [hunk 89]
```diff
@@ -1,29 +1,63 @@
...
+                 . 'return ' . var_export( $config, true ) . ';' . "\n"
+                 . '?>' . "\n" ;
```
Comment (dionyziz) [inline helpers/config.php:32]: Consider combining into `"?>\n"`

File: helpers/config.php (hunk 62 above)
Comment (dionyziz) [inline helpers/config.php:40]: Parentheses immediately between regexp introducer characters `/(...)/` is unnecessary.

Comment (dionyziz) [inline helpers/config.php:40]: Why does your character class need to include all characters except `(<)|(\?)`? It seems that the only line you need to exclude starts with either `<` in `<?php` or with `?` in `?>`. Furthermore, your character class excludes `(` twice. Perhaps use `[^<?]`. Remember that parentheses within `[]` do not group - they indicate literal characters within the character class mini-language.

File: helpers/file.php [hunk 90]
```diff
@@ -0,0 +1,22 @@
...
+        if ( !file_exists( $filename ) ) {
+            @touch( $filename );
+        }
+        if ( is_writable( $filename ) ) {
+            $success = file_put_contents( $filename, $content );
+        }
+        if ( empty( $success ) ) {
+            throw new FileNotWritableException( $filename, $content );
+        }
```
Comment (dionyziz) [inline helpers/file.php]: I'm still not sure why you can't simply call `@file_put_contents` here - without using `touch` or `is_writable` at all. Here's my suggestion: Just call `@file_put_contents` and check for success. If the file is not touchable, or if it is not writable, then `file_put_contents` will return `false`. This will simplify the code in this function to just 4 lines.

File: tests/helpers/file.php [hunk 91]
```diff
@@ -0,0 +1,71 @@
...
+            $this->emptyWritableDirectory();
+            $this->readOnlyFile();
+        }
+        private function safeUnlink( $filename ) {
+            if ( file_exists( $filename ) ) {
+
+                chmod( $filename, 0666 );
+
+                if ( is_dir( $filename ) ) {
+                    rmdir( $this->directory );
```
Comment (dionyziz) [inline tests/helpers/file.php]: `$filename`

File: tests/helpers/config.php (hunk 83 above)
Comment (dionyziz) [inline tests/helpers/config.php:47]: OK

File: tests/helpers/file.php (hunk 82 above)
Comment (dionyziz) [inline tests/helpers/file.php]: I see.

**Comment by dionyziz** [comment]
Fixes #62

**Comment by dionyziz** [comment]
Fix build

File: controllers/dbconfig.php [hunk 92]
```diff
@@ -0,0 +1,29 @@
...
+                go();
+            }
+            catch ( FileNotWritableException $e ) {
+                $content = $e->content;
+                require_once 'views/database/notwritable.php';
+            }
+        }
+        public function createView( $error, $dbSaid ) {
+            global $config;
+            $oldConfig = [ 'db' => [
```
Comment (vitsalis) [inline controllers/dbconfig.php]: We don't use that style anywhere else in our code. I suggest you write this as:

```
$oldConfig = [
    'db' => [
           'user' => ....
     ]
]
```

File: helpers/config.php [hunk 93]
```diff
@@ -15,15 +15,49 @@ function getBase() {
...
         }
-        $config = $config[ $env ];
+        $config = $config[ $environment ];
         $config[ 'root' ] = getcwd();
         $config[ 'base' ] = getBase();
         return $config;
     }
+    function formatConfig( $config ) {
+        $content = '<?php' . "\n"
+                 . 'return ' . var_export( $config, true ) . ';' . "\n"
```
Comment (vitsalis) [inline helpers/config.php:31]: Compine into `";\n"`

File: models/db.php [hunk 94]
```diff
@@ -1,4 +1,18 @@
 <?php
+    function dbInit() {
+        global $config;
+
+        $dbConnected = mysql_connect( $config[ 'db' ][ 'host' ],
```
Comment (vitsalis) [inline models/db.php]: Our style is:

```
mysql_connect(
    $config[ 'db' ][ 'host' ],
    $config[ 'db' ][ 'pass' ],
    $config[ 'db' ][ 'user' ]
);
```

File: helpers/config.php (hunk 93 above)
Comment (bugos) [inline helpers/config.php:31]: @dionyziz also suggested this. I believe that it's more readable and more extensible this way.

File: tests/helpers/array.php [hunk 95]
```diff
@@ -0,0 +1,53 @@
...
+            $updatedArray = [
+                'name' => 'bugos',
+                'email' => 'bugos@gmail.com',
+                'technologies' => [
+                    'c++' => 5,
+                    'python' => 3,
+                    'php' => 3
+                ]
+            ];
+            $this->assertSame( [
```
Comment (vitsalis) [inline tests/helpers/array.php]: opening `[` should be on the next line

File: tests/helpers/array.php [hunk 96]
```diff
@@ -0,0 +1,53 @@
...
+            $slicedArray = [
+                'name' => 'bugos',
+                'email' => NULL,
+                'technologies' => [
+                    'c++' => 5,
+                    'python' => 3,
+                    'php' => NULL
+                ]
+            ];
+            $this->assertSame( [
```
Comment (vitsalis) [inline tests/helpers/array.php]: same as above

File: tests/models/file.php [hunk 97]
```diff
@@ -1,3 +1,91 @@
+<<<<<<< HEAD:tests/helpers/file.php
```
Comment (vitsalis) [inline tests/models/file.php]: what's this?

File: tests/models/file.php [hunk 98]
```diff
@@ -1,3 +1,91 @@
...
+                'FileNotWritableException',
+                'safeWrite() must throw an Exception when attempting to write a read-only file',
+                function( FileNotWritableException $e ) {
+                    $this->assertEquals( $this->filename, $e->filename );
+                    $this->assertEquals( $this->content, $e->content );
+                }
+            );
+        }
+        public function testSafeWrite() {
+            //$this->readOnlyDirectory(); // This test is not functional yet.
```
Comment (vitsalis) [inline tests/models/file.php]: space after `//` and why do you have two of them?

File: tests/models/file.php [hunk 99]
```diff
@@ -1,3 +1,91 @@
...
+            $this->safeUnlink( $this->directory );
+
+            $this->rrmdir( $this->copyPath );
+            $this->rrmdir( $this->mockPath );
+        }
+    }
+
+    return new FileHelperTest();
+?>
+=======
```
Comment (vitsalis) [inline tests/models/file.php]: ?

File: tests/models/file.php [hunk 100]
```diff
@@ -20,3 +108,4 @@ public function tearDown() {
     }
     return new TestFile();
 ?>
+>>>>>>> a5f454dcc89a4341ae203ffbfd8148972b9da692:tests/models/file.php
```
Comment (vitsalis) [inline tests/models/file.php]: ?

File: tests/models/user.php [hunk 101]
```diff
@@ -211,7 +199,7 @@ public function testSaveImage() {
             $user->image = $image;
             $user->save();
             $dbUser = new User( $user->id );
-            $this->assertSame( 1, $dbUser->image->id, 'The imageid must be correctly stored in the database' );
+            $this->assertSame( 1, $dbUser->image->id, 'The $imageid must be correctly stored in the database' );
```
Comment (vitsalis) [inline tests/models/user.php]: we don't need `$` in the message. It's only needed for php variables.

File: tests/models/user.php [hunk 102]
```diff
@@ -223,30 +211,28 @@ public function testWinCount() {
             $dbUser = new User( $user->id );
             $winCount = $dbUser->getWinCount();
 
-            $this->assertTrue( isset( $dbUser->winCount ), 'winCount must be set for each user' );
-            $this->assertSame( 1, $winCount, 'winCount must represent the number of wins a user has' );
+            $this->assertTrue( isset( $dbUser->winCount ), '$winCount must be set for each user' );
+            $this->assertSame( 1, $winCount, '$winCount must represent the number of wins a user has' );
```
Comment (vitsalis) [inline tests/models/user.php]: same as above for these two

File: tests/models/user.php (hunk 101 above)
Comment (bugos) [inline tests/models/user.php]: I added it to make it clear that we are talking about php variables.
